### ISSUE TITLE
您好，我想问一下，match_results.txt 这个数据集的出处

### ISSUE THREAD

**Issue by RookieoftheYear** [maxuewei2/MFBPR_TransR#1]
您好，我想问一下，match_results.txt 这个数据集的出处

**Comment by maxuewei2** [comment]
@RookieoftheYear    这个是我自己处理得到的数据集，处理过程如下：首先得到 [movie-lens](https://grouplens.org/datasets/movielens/) 数据集和 [YAGO知识图谱数据](https://www.mpi-inf.mpg.de/departments/databases-and-information-systems/research/yago-naga/yago/downloads/) (我应该是只用了 yagoFacts)，然后对于 movie-lens 中的电影，在 YAGO 中寻找相关的 fact，match_results.txt 即是所有匹配到的 fact。
具体如下
![image](https://user-images.githubusercontent.com/13077408/56665085-f83b0800-66db-11e9-8b3b-cb4fd8064a96.png)
